name: simple tests
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    name: "Fake test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test for composer
        id: composer_exists
        run: |
            sleep 40
            if [[ -f 'composer.json' ]]; then
              response="pass"
            else
              response="fail"
            fi
            ls -al
            echo "::set-output name=testresult::${response}"
      - name: Check Pass
        if: steps.composer_exists.outputs.testresult != 'pass'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Composer Does Not Exist!')